routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Dashboard
Route::resource('dashboard', 'RoutingControllers\DashboardController');
// Company
Route::resource('company', 'Maintenance\CompanyController');
Route::get('company/create',['as'=>'company.add','uses'=>'Maintenance\CompanyController@add']);
Route::post('company/delete',['as'=>'company.delete','uses'=>'Maintenance\CompanyController@delete']);
// Branches
Route::resource('branch', 'Maintenance\BranchController');
Route::get('branch/create',['as'=>'branch.add','uses'=>'Maintenance\BranchController@add']);
Route::post('branch/delete',['as'=>'branch.delete','uses'=>'Maintenance\BranchController@delete']);
// Users
Route::resource('users', 'Maintenance\UserController');
Route::get('users/create',['as'=>'users.add','uses'=>'Maintenance\UserController@add']);
Route::post('users/delete',['as'=>'users.delete','uses'=>"Maintenance\UserController@delete"]);
Route::get('users/branches/{id}',['as'=>'users.branches','uses'=>'Maintenance\UserController@branches']);
Route::post('users/addbranch',['as'=>'users.add_branch','uses'=>'Maintenance\UserController@add_branch']);
// Sales
Route::resource('sales', 'SalesReport\SalesSummaryController');

app/Http/Controllers/Maintenance/BranchController.php
<?php

namespace App\Http\Controllers\Maintenance;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Repositories\Interfaces\CompanyBranchRepositoryInterface;

use Auth;

class BranchController extends Controller
{
	protected $branch;
	protected $request;
	public function __construct(CompanyBranchRepositoryInterface $branch, Request $request)
	{
		$this->branch = $branch;
		$this->request = $request;
	}

    public function index()
    {
        if(empty(Auth::user())){
            return redirect('/')->with('session_expired', 'Logout');
        }
    	$branches = $this->branch->All();

    	return view('branch.index', compact('branches'));
    }

    public function add()
    {
    	return view('branch.create');
    }

    public function store(Request $request)
    {
    	if($request->area == '' || $request->area == null){
    		$area = 0.00;
    	}else{
    		$area = $request->area;
    	}
    	$postdata['company_id'] = $request->company_id;
    	$postdata['branch_code'] = $request->branch_code;
    	$postdata['branch_name'] = strtoupper($request->branch_name);
    	$postdata['area'] = $area;

    	$this->branch->Store($postdata);

    	return redirect('branch')->with('is_added', 'Success');
    }

    public function show($id)
    {
    	$branch = $this->branch->Show($id);

    	return view('branch.edit',compact('branch'));
    }

    public function update(Request $request, $id)
    {
    	if($request->area == '' || $request->area == null){
    		$area = 0.00;
    	}else{
    		$area = $request->area;
    	}
    	$postdata['company_id'] = $request->company_id;
    	$postdata['branch_name'] = strtoupper($request->branch_name) ;
    	$postdata['branch_code'] = $request->branch_code;
    	$postdata['area'] = $area;

    	$this->branch->Update($postdata, $id);

    	return redirect('branch')->with('is_success', 'Success');
    }

    public function delete(Request $request)
    {
    	$id = $request->id;

    	$this->branch->Delete($id);

    	return redirect('branch')->with('is_deleted', 'Success');
    }
}

resources/views/branch/create.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">Branches</li>
                </ol>
            </div>
            <h4 class="page-title">Add Branch</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <div class="col-6">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"></h4>
            </div>
            {{ Form::open(array('route' => 'branch.store', 'method' => 'POST', 'class' => 'form-horizontal form-label-left')) }}
            <div class="col-md-12">
                <div class="form-group">
                    {{Form::label('id','Branch ID')}}
                    <input type="text" class="form-control" name="company_id" required="">
                </div>
                <div class="form-group">
                    {{Form::label('code','Branch Code')}}
                    <input type="text" class="form-control" name="branch_code" required="">
                </div>
                <div class="form-group">
                    {{Form::label('name','Branch Name')}}
                    <input type="text" class="form-control" name="branch_name" required="">
                </div>
                <div class="form-group">
                    {{Form::label('area','Area')}}
                    <input type="number" value="0.00" class="form-control" name="area" required="">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-xs" type="submit"> Save</button>
                    <a href="{{route('branch.index')}}" class="btn btn-xs btn-warning"> Cancel</a>
                </div>
            </div>
            {{Form::close()}}
        </div>
    </div>
</div>
@endsection

resources/views/branch/edit.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">Branches</li>
                </ol>
            </div>
            <h4 class="page-title">Branch Details</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <div class="col-6">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"></h4>
            </div>
            {{ Form::open(array('route' => array('branch.update', $branch->id), 'method' => 'PUT', 'class' => 'form-horizontal form-label-left')) }}
            <div class="col-md-12">
                <div class="form-group">
                    {{Form::label('id','Branch ID')}}
                    <input type="text" class="form-control" name="company_id" required="" value="{{$branch->company_id}}">
                </div>
                <div class="form-group">
                    {{Form::label('code','Branch Code')}}
                    <input type="text" class="form-control" name="branch_code" required="" value="{{$branch->branch_code}}">
                </div>
                <div class="form-group">
                    {{Form::label('name','Branch Name')}}
                    <input type="text" class="form-control" name="branch_name" required="" value="{{$branch->branch_name}}">
                </div>
                <div class="form-group">
                    {{Form::label('area','Area')}}
                    <input type="number" value="0.00" class="form-control" name="area" required="" value="{{$branch->area}}">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-xs" type="submit"> Save</button>
                    <a href="{{route('branch.index')}}" class="btn btn-xs btn-warning"> Cancel</a>
                </div>
            </div>
            {{Form::close()}}
        </div>
    </div>
</div>
@endsection

resources/views/branch/index.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-lg-12 animated flash">
        <?php if (session('is_success')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">Branch was successfully updated!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
        <?php if (session('is_added')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">Branch was successfully added!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
        <?php if (session('is_deleted')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">Branch was successfully deleted!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
    </div>
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">Branches</li>
                </ol>
            </div>
            <h4 class="page-title">Branches</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
	<div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"><a href="{{route('branch.add')}}" class="btn btn-xs btn-success"> Add Branch</a></h4>        
                <table id="datatable" class="table table-bordered">
                	<thead>
                		<tr>
                			<th>Branch Code</th>
                			<th>Branch Name</th>
                			<th>Action</th>
                		</tr>
                	</thead>
                	<tbody>
                		@foreach($branches as $branch)
                		<tr>
                			<td>{{$branch->branch_code}}</td>
                			<td>{{$branch->branch_name}}</td>
                			<td>
                				<a class="btn btn-primary btn-xs" href="{{ route('branch.show', $branch->id)}}">Edit</a>
                                {{Form::open(array('route'=>'branch.delete', 'method' => 'POST', 'class' => 'form-horizontal form-label-left'))}}
                                    {{Form::hidden('id', $branch->id)}}
                                    <button class="btn btn-xs btn-danger"> Delete</button>
                                {{Form::close()}}
                			</td>
                		</tr>
                		@endforeach
                	</tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection