routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Dashboard
Route::resource('dashboard', 'RoutingControllers\DashboardController');
// Company
Route::resource('company', 'Maintenance\CompanyController');
Route::get('company/create',['as'=>'company.add','uses'=>'Maintenance\CompanyController@add']);
Route::post('company/delete',['as'=>'company.delete','uses'=>'Maintenance\CompanyController@delete']);
// Branches
Route::resource('branch', 'Maintenance\BranchController');
Route::get('branch/create',['as'=>'branch.add','uses'=>'Maintenance\BranchController@add']);
Route::post('branch/delete',['as'=>'branch.delete','uses'=>'Maintenance\BranchController@delete']);
// Users
Route::resource('users', 'Maintenance\UserController');
Route::get('users/create',['as'=>'users.add','uses'=>'Maintenance\UserController@add']);
Route::post('users/delete',['as'=>'users.delete','uses'=>"Maintenance\UserController@delete"]);
Route::get('users/branches/{id}',['as'=>'users.branches','uses'=>'Maintenance\UserController@branches']);
Route::post('users/addbranch',['as'=>'users.add_branch','uses'=>'Maintenance\UserController@add_branch']);
// Sales
Route::resource('sales', 'SalesReport\SalesSummaryController');

app/Models/Maintenance/Company.php
<?php

namespace App\Models\Maintenance;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'companies';
    protected $fillable = ['company_code', 'company_name'];
}

app/Http/Controllers/Maintenance/CompanyController.php
<?php

namespace App\Http\Controllers\Maintenance;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Repositories\Interfaces\CompanyRepositoryInterface;

use Auth;

class CompanyController extends Controller
{
	protected $company;
	protected $request;

	public function __construct(CompanyRepositoryInterface $company, Request $request)
	{
		$this->request = $request;
		$this->company = $company;
	}
    public function index()
    {
        if(empty(Auth::user())){
            return redirect('/')->with('session_expired', 'Logout');
        }
    	$companies = $this->company->All();

    	return view('company.index',compact('companies'));
    }
    public function show($id)
    {
    	$cmp = $this->company->show($id);

    	return view('company.edit',compact('cmp'));
    }
    public function update(Request $request, $id)
    {
    	$postdata['company_code'] = $request->company_code;
    	$postdata['company_name'] = $request->company_name;

    	$this->company->Update($postdata, $id);

    	return redirect('company')->with('is_success', 'Success');
    }

    public function add()
    {
    	return view('company.create');
    }

    public function store(Request $request)
    {
    	$postdata['company_code'] = $request->company_code;
    	$postdata['company_name'] = $request->company_name;

    	$this->company->Store($postdata);

    	return redirect('company')->with('is_added', 'Sucess');
    }

    public function delete(Request $request)
    {
    	$id = $request->id;

    	$this->company->Delete($id);

    	return redirect('company')->with('is_deleted', 'Success');
    }
}

resources/views/company/create.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">Companies</li>
                </ol>
            </div>
            <h4 class="page-title">Add Company</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <div class="col-6">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"></h4>
            </div>
            {{ Form::open(array('route' => 'company.store', 'method' => 'POST', 'class' => 'form-horizontal form-label-left')) }}
            <div class="col-md-12">
                <div class="form-group">
                    {{Form::label('code','Company Code')}}
                    <input type="text" class="form-control" name="company_code" required="">
                </div>
                <div class="form-group">
                    {{Form::label('name','Company Name')}}
                    <input type="text" class="form-control" name="company_name" required="">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-xs" type="submit"> Save</button>
                    <a href="{{route('company.index')}}" class="btn btn-xs btn-warning"> Cancel</a>
                </div>
            </div>
            {{Form::close()}}
        </div>
    </div>
</div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">Companies</li>
                </ol>
            </div>
            <h4 class="page-title">Company Details</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <div class="col-6">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"></h4>
            </div>
            {{ Form::open(array('route' => array('company.update', $cmp->id), 'method' => 'PUT', 'class' => 'form-horizontal form-label-left')) }}
            <div class="col-md-12">
                <div class="form-group">
                    {{Form::label('code','Company Code')}}
                    <input type="text" class="form-control" name="company_code" value="{{$cmp->company_code}}">
                </div>
                <div class="form-group">
                    {{Form::label('name','Company Name')}}
                    <input type="text" class="form-control" name="company_name" value="{{$cmp->company_name}}">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-xs" type="submit"> Save</button>
                    <a href="{{route('company.index')}}" class="btn btn-xs btn-warning"> Cancel</a>
                </div>
            </div>
            {{Form::close()}}
        </div>
    </div>
</div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-lg-12 animated flash">
        <?php if (session('is_success')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">Company was successfully updated!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
        <?php if (session('is_added')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">Company was successfully added!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
        <?php if (session('is_deleted')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">Company was successfully deleted!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
    </div>
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">Companies</li>
                </ol>
            </div>
            <h4 class="page-title">Companies</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
	<div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"><a href="{{route('company.add')}}" class="btn btn-xs btn-success"> Add Company</a></h4>        
                <table id="datatable" class="table table-bordered">
                	<thead>
                		<tr>
                			<th>Company Code</th>
                			<th>Company Name</th>
                			<th>Action</th>
                		</tr>
                	</thead>
                	<tbody>
                		@foreach($companies as $company)
                		<tr>
                			<td>{{$company->company_code}}</td>
                			<td>{{$company->company_name}}</td>
                			<td>
                				<a class="btn btn-primary btn-xs" href="{{ route('company.show', $company->id)}}">Edit</a>
                                {{Form::open(array('route'=>'company.delete','method'=>'POST'))}}
                                    {{Form::hidden('id', $company->id)}}
                                    <button class="btn btn-xs btn-danger"> Delete</button>
                                {{Form::close()}}
                			</td>
                		</tr>
                		@endforeach
                	</tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection