routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Dashboard
Route::resource('dashboard', 'RoutingControllers\DashboardController');
// Company
Route::resource('company', 'Maintenance\CompanyController');
Route::get('company/create',['as'=>'company.add','uses'=>'Maintenance\CompanyController@add']);
Route::post('company/delete',['as'=>'company.delete','uses'=>'Maintenance\CompanyController@delete']);
// Branches
Route::resource('branch', 'Maintenance\BranchController');
Route::get('branch/create',['as'=>'branch.add','uses'=>'Maintenance\BranchController@add']);
Route::post('branch/delete',['as'=>'branch.delete','uses'=>'Maintenance\BranchController@delete']);
// Users
Route::resource('users', 'Maintenance\UserController');
Route::get('users/create',['as'=>'users.add','uses'=>'Maintenance\UserController@add']);
Route::post('users/delete',['as'=>'users.delete','uses'=>"Maintenance\UserController@delete"]);
Route::get('users/branches/{id}',['as'=>'users.branches','uses'=>'Maintenance\UserController@branches']);
Route::post('users/addbranch',['as'=>'users.add_branch','uses'=>'Maintenance\UserController@add_branch']);
// Sales
Route::resource('sales', 'SalesReport\SalesSummaryController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'password', 'active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->hasOne('App\Models\Maintenance\RoleUser','user_id','id');
    }
}

app/Http/Controllers/Maintenance/UserController.php
<?php

namespace App\Http\Controllers\Maintenance;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

use App\Repositories\Interfaces\UserRepositoryInterface;
use App\Repositories\Interfaces\UserBranchRepositoryInterface;
use App\Repositories\Interfaces\CompanyBranchRepositoryInterface;

use Auth;

class UserController extends Controller
{
	protected $user;

    protected $request;

    protected $ubranch;

	protected $branch;

    public function __construct(
        UserRepositoryInterface $user, 
        UserBranchRepositoryInterface $ubranch, 
        CompanyBranchRepositoryInterface $branch,
        Request $request)
    {
    	$this->user = $user;
        $this->ubranch = $ubranch;
        $this->branch = $branch;
    	$this->request = $request;
    }

    public function index()
    {   
        if(empty(Auth::user())){
            return redirect('/')->with('session_expired', 'Logout');
        }
    	$users = $this->user->All();

    	return view('user.index', compact('users'));
    }

    public function add()
    {
        $roles = $this->user->getRoles();
    	return view('user.create',compact('roles'));
    }

    public function store(Request $request)
    {
    	if(!empty($request)){
            $this->user->Store($request, $request->role_id);
    		return redirect('users')->with('is_added', 'Success');
    	}
    }

    public function show($id)
    {
    	$user = $this->user->Show($id);
        $my_role = $this->user->MyRole($id);
        $roles = $this->user->getRoles();
    	return view('user.edit',compact('user','roles','my_role'));
    }

    public function update(Request $request, $id)
    {
    	if(!empty($request)){
    		$postdata['name'] = $request->name;
    		$postdata['username'] = $request->username;
    		$postdata['email'] = $request->email;

    		$this->user->Update($postdata, $id, $request->role_id);

    		return redirect('users')->with('is_success', 'Success');
    	}
    }

    public function delete(Request $request)
    {
    	$id = $request->id;

    	$this->user->Delete($id);

    	return redirect()->back()->with('is_deleted', 'Success');
    }

    public function branches($id)
    {
        $id = $id;

        $my_branches = $this->ubranch->MyBranches($id);

        $branches = $this->branch->All();

        $user = $id;

        return view('user.branch',compact('my_branches','branches','user'));
    }

    public function add_branch(Request $request)
    {
        $this->ubranch->SearchAndDelete($request->user_id);

        $this->ubranch->SaveBranches($request->user_id, $request->branch);
        
        return redirect()->back()->with('is_success', 'Success');
    }
}

resources/views/user/branch.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-lg-12 animated flash">
        <?php if (session('is_success')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">Branches were successfully tagged to this user!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
        <?php if (session('is_added')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">User was successfully added!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
        <?php if (session('is_deleted')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">User was successfully deleted!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
    </div>
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">User Branches</li>
                </ol>
            </div>
            <h4 class="page-title">User Branches</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
	<div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"></h4>      
                {{Form::open(array('route'=>'users.add_branch', 'method'=>'POST'))}}
                <table id="datatable" class="table table-bordered">
                	<thead>
                		<tr>
                			<th>Company</th>
                            <th>Branch Code</th>
                			<th>Branch Name</th>
                			<th>Action</th>
                		</tr>
                	</thead>
                	<tbody>
                		@foreach($branches as $branch)
                		<tr>
                            <td>{{$branch->company->company_name}}</td>
                			<td>{{$branch->branch_code}}</td>
                            <td>{{$branch->branch_name}}</td>
                            <td>
                                {{ Form::checkbox('branch[]', $branch->id, (in_array($branch->id, $my_branches) ? true : false)) }}
                            </td>
                		</tr>
                		@endforeach
                	</tbody>
                </table>
                {{ Form::hidden('user_id', $user) }}
                <button type="submit" class="btn btn-xs btn-primary pull-right"> Save</button>
                <a href="{{route('users.index')}}" class="btn btn-xs btn-danger pull-right"> Cancel</a>
                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/create.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">Users</li>
                </ol>
            </div>
            <h4 class="page-title">Add User</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <div class="col-6">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"></h4>
            </div>
            {{ Form::open(array('route' => 'users.store', 'method' => 'POST', 'class' => 'form-horizontal form-label-left')) }}
            <div class="col-md-12">
                <div class="form-group">
                    {{Form::label('name','Name Of User')}}
                    <input type="text" class="form-control" name="name" required="">
                </div>
                <div class="form-group">
                    {{Form::label('username','Username')}}
                    <input type="text" class="form-control" name="username" required="">
                </div>
                <div class="form-group">
                    {{Form::label('email','Email')}}
                    <input type="email" class="form-control" name="email" required="">
                </div>
                <div class="form-group">
                    {{Form::label('acc_type','Select Role Of Account')}}
                    <select name="role_id" class="form-control" required="">
                        <option value=""> </option>
                        @foreach($roles as $role)
                        <option value="{{$role->id}}">{{strtoupper($role->role_name)}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    {{Form::label('pass','Password')}}
                    <input type="password" class="form-control" name="password" required="">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-xs" type="submit"> Save</button>
                    <a href="{{route('users.index')}}" class="btn btn-xs btn-warning"> Cancel</a>
                </div>
            </div>
            {{Form::close()}}
        </div>
    </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">Users</li>
                </ol>
            </div>
            <h4 class="page-title">User Details</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <div class="col-6">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"></h4>
            </div>
            {{ Form::open(array('route' => array('users.update',$user->id), 'method' => 'PUT', 'class' => 'form-horizontal form-label-left')) }}
            <div class="col-md-12">
                <div class="form-group">
                    {{Form::label('name','Name Of User')}}
                    <input type="text" class="form-control" name="name" required="" value="{{$user->name}}">
                </div>
                <div class="form-group">
                    {{Form::label('username','Username')}}
                    <input type="text" class="form-control" name="username" required="" value="{{$user->username}}">
                </div>
                <div class="form-group">
                    {{Form::label('email','Email')}}
                    <input type="email" class="form-control" name="email" required="" value="{{$user->email}}">
                </div>
                <div class="form-group">
                    {{Form::label('acc_type','Role Of Account')}}
                    <select name="role_id" class="form-control">
                        @foreach($roles as $role)
                        @if($role->id == $my_role->role_id)
                        <option value="{{$role->id}}" selected="">{{strtoupper($role->role_name)}}</option>
                        @else
                        <option value="{{$role->id}}">{{strtoupper($role->role_name)}}</option>
                        @endif
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-xs" type="submit"> Save</button>
                    <a href="{{route('users.index')}}" class="btn btn-xs btn-warning"> Cancel</a>
                </div>
            </div>
            {{Form::close()}}
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.master')
@section('main_body')
<div class="row">
    <div class="col-lg-12 animated flash">
        <?php if (session('is_success')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">User was successfully updated!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
        <?php if (session('is_added')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">User was successfully added!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
        <?php if (session('is_deleted')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
                <center><p style="color:white">User was successfully deleted!<i class="fa fa-check"></i></p></center>                
            </div>
        <?php endif;?>
    </div>
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group float-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Fortune Wear</a></li>
                    <li class="breadcrumb-item active">Users</li>
                </ol>
            </div>
            <h4 class="page-title">Users</h4>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
	<div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">            
                <h4 class="mt-0 header-title"><a href="{{route('users.add')}}" class="btn btn-xs btn-success"> Add User</a></h4>        
                <table id="datatable" class="table table-bordered">
                	<thead>
                		<tr>
                			<th>Name Of User</th>
                            <th>Username</th>
                			<th>Account Type</th>
                			<th>Action</th>
                		</tr>
                	</thead>
                	<tbody>
                		@foreach($users as $user)
                		<tr>
                            <td>{{$user->name}}</td>
                			<td>{{$user->username}}</td>
                            <td>{{$user->account_type}}</td>
                            <td>
                                <a class="btn btn-xs btn-info" href="{{route('users.show', $user->id)}}"> Edit</a>
                                <a class="btn btn-xs btn-primary" href="{{route('users.branches', $user->id)}}"> Map Branches</a>
                                {{Form::open(array('route'=>'users.delete', 'method'=>'POST'))}}
                                {{Form::hidden('id',$user->id)}}
                                <button class="btn btn-xs btn-danger"> Delete</button>
                                {{Form::close()}}
                            </td>
                		</tr>
                		@endforeach
                	</tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection