routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Dashboard
Route::resource('dashboard', 'RoutingControllers\DashboardController');
// Company
Route::resource('company', 'Maintenance\CompanyController');
Route::get('company/create',['as'=>'company.add','uses'=>'Maintenance\CompanyController@add']);
Route::post('company/delete',['as'=>'company.delete','uses'=>'Maintenance\CompanyController@delete']);
// Branches
Route::resource('branch', 'Maintenance\BranchController');
Route::get('branch/create',['as'=>'branch.add','uses'=>'Maintenance\BranchController@add']);
Route::post('branch/delete',['as'=>'branch.delete','uses'=>'Maintenance\BranchController@delete']);
// Users
Route::resource('users', 'Maintenance\UserController');
Route::get('users/create',['as'=>'users.add','uses'=>'Maintenance\UserController@add']);
Route::post('users/delete',['as'=>'users.delete','uses'=>"Maintenance\UserController@delete"]);
Route::get('users/branches/{id}',['as'=>'users.branches','uses'=>'Maintenance\UserController@branches']);
Route::post('users/addbranch',['as'=>'users.add_branch','uses'=>'Maintenance\UserController@add_branch']);
// Sales
Route::resource('sales', 'SalesReport\SalesSummaryController');

resources/views/includes/sidebar.blade.php
<div class="sidebar-inner slimscrollleft" id="sidebar-main">

                    <div id="sidebar-menu">
                        <ul>
                            <li class="menu-title">Main</li>

                            <li>
                                <a href="{{route('dashboard.index')}}" class="waves-effect">
                                    <i class="fa fa-tachometer-alt"></i>
                                    <span> Dashboard</span>
                                </a>
                            </li>
                            @if(Auth::user()->role->role_id == 1)
                            <li class="menu-title">Maintenance</li>
                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect">
                                    <i class="fa fa-sliders-h"></i>
                                    <span> Maintenance </span>
                                    <span class="float-right">
                                        <i class="mdi mdi-chevron-right"></i>
                                    </span>
                                </a>
                                <ul class="list-unstyled">
                                    <li>
                                        <a href="{{route('users.index')}}" class="waves-effect">
                                            <i class="fa fa-users"></i>
                                            <span> Users </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{route('branch.index')}}" class="waves-effect">
                                            <i class="fa fa-sitemap"></i>
                                            <span> Branches </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{route('company.index')}}" class="waves-effect">
                                            <i class="fa fa-building"></i>
                                            <span> Companies </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            @endif
                            <li class="menu-title">Sales</li>
                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect">
                                    <i class="fa fa-copy"></i>
                                    <span> Sales Report </span>
                                    <span class="float-right">
                                        <i class="mdi mdi-chevron-right"></i>
                                    </span>
                                </a>
                                <ul class="list-unstyled">
                                    <li>
                                        <a href="{{route('sales.index')}}" class="waves-effect">
                                            <i class="fa fa-file"></i>
                                            <span> Sales </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <!-- <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect">
                                    <i class="mdi mdi-cards"></i>
                                    <span> Forms </span>
                                    <span class="badge badge-pill badge-info float-right">8</span>
                                </a>
                                <ul class="list-unstyled">
                                    <li>
                                        <a href="form-elements.html">Form Elements</a>
                                    </li>
                                    <li>
                                        <a href="form-validation.html">Form Validation</a>
                                    </li>
                                    <li>
                                        <a href="form-advanced.html">Form Advanced</a>
                                    </li>
                                    <li>
                                        <a href="form-mask.html">Form Mask</a>
                                    </li>
                                    <li>
                                        <a href="form-editors.html">Form Editors</a>
                                    </li>
                                    <li>
                                        <a href="form-uploads.html">Form File Upload</a>
                                    </li>
                                </ul>
                            </li> -->
                            <!-- <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect">
                                    <i class="mdi mdi-emoticon-poop"></i>
                                    <span> Icons </span>
                                    <span class="float-right">
                                        <i class="mdi mdi-chevron-right"></i>
                                    </span>
                                </a>
                                <ul class="list-unstyled">
                                    <li>
                                        <a href="icons-material.html">Material Design</a>
                                    </li>
                                    <li>
                                        <a href="icons-fontawesome.html">Font Awesome</a>
                                    </li>
                                    <li>
                                        <a href="icons-themify.html">Themify Icons</a>
                                    </li>
                                </ul>
                            </li> -->
                            <!-- <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect">
                                    <i class="mdi mdi-chart-areaspline"></i>
                                    <span> Charts </span>
                                    <span class="float-right">
                                        <i class="mdi mdi-chevron-right"></i>
                                    </span>
                                </a>
                                <ul class="list-unstyled">
                                    <li>
                                        <a href="charts-morris.html">Morris Chart</a>
                                    </li>
                                    <li>
                                        <a href="charts-chartist.html">Chartist Chart</a>
                                    </li>
                                    <li>
                                        <a href="charts-chartjs.html">Chartjs Chart</a>
                                    </li>
                                    <li>
                                        <a href="charts-flot.html">Flot Chart</a>
                                    </li>
                                    <li>
                                        <a href="charts-c3.html">C3 Chart</a>
                                    </li>
                                    <li>
                                        <a href="charts-xchart.html">X Chart</a>
                                    </li>
                                    <li>
                                        <a href="charts-other.html">Jquery Knob Chart</a>
                                    </li>
                                </ul>
                            </li> -->
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <!-- end sidebarinner -->
            </div>

resources/views/includes/topbar.blade.php
<div class="topbar">
    <nav class="navbar-custom">
        <div class="dropdown notification-list nav-pro-img">
            <div class="list-inline-item hide-phone app-search">
                <form role="search" class="">
                    <div class="form-group pt-1">
                    </div>
                </form>
            </div>
        </div>
        <ul class="list-inline float-right mb-0 mr-3">
            <!-- language-->
            <li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none waves-effect nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false"
                    aria-expanded="false">
                    <span class="float-right" style="color: white;">
                        <i class="fa fa-user-circle fa-2x"></i>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                    <div class="dropdown-item noti-title">
                        <h5>
                            Welcome {{strtoupper(Auth::user()->username)}}
                        </h5>
                    </div>
                    <a class="dropdown-item" style="cursor: pointer;" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
        <ul class="list-inline menu-left mb-0">
            <li class="float-left">
                <button class="button-menu-mobile open-left waves-light waves-effect">
                    <i class="mdi mdi-menu"></i>
                </button>
            </li>
        </ul>
        <div class="clearfix"></div>
    </nav>
</div>